name: CI for C++ and Arduino

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  cpp-arduino-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'

      - name: Download platform Arduino AVR
        run: arduino-cli core install arduino:avr

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Build with Bat file
        run: ci/Build.bat

      - name: Run tests
        run: ci/RunTests.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/*

      - name: Upload test result artifacts
        uses: actions/upload-artifact@v3
        with:
          name: testresult-artifacts
          path: TestResult/*