name: CI for C++ and Arduino

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  cpp-arduino-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'

      - name: Download platform Arduino AVR
        run: arduino-cli core install arduino:avr

      - name: Install Doxygen using Chocolatey
        run: |
	Invoke-WebRequest -Uri "https://doxygen.nl/files/doxygen-1.9.6.1-setup.exe" -OutFile "doxygen-setup.exe"
        Start-Process -Wait -FilePath "doxygen-setup.exe" -ArgumentList "/SILENT", "/DIR=C:\Program Files\doxygen"
        $env:Path += ";C:\Program Files\doxygen\bin"

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Build with Bat file
        run: ci/Build.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/*

      - name: Generate documentation using Doxygen
        run: |
          cd doc
          doxygen Doxyfile

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: doc/output/html
